[project]
authors = ["Arjo Chakravarty <arjo129@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "gz-rl-demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda = ">=12.6.2,<13"
libcublas = ">=12.6.3.3,<13"
gz-sim8 = ">=8.6.0,<9"
gz-transport13 = ">=13.4.0,<14"
sdformat14 = ">=14.5.0,<15"
protobuf = "==5.27.5"

[system-requirements]
cuda = "12" # or any 
